---
# LUNA OS - Calamares Settings
# Offline installer configuration

modules-search: [ local ]

instances:
  - id: offline
    module: packages
    config: packages_offline.conf

  - id: postinstall
    module: shellprocess
    config: shellprocess_postinstall.conf

sequence:
  - show:
    - welcome
    - locale
    - keyboard
    - partition
    - users
    - summary
  - exec:
    - partition
    - mount
    - unpackfs
    - machineid
    - locale
    - keyboard
    - localecfg
    - fstab
    - initcpiocfg
    - initcpio
    - users
    - displaymanager
    - networkcfg
    - packages@offline
    - hwclock
    - services-systemd
    - grubcfg
    - bootloader
    - shellprocess@postinstall
    - umount
  - show:
    - finished

branding: lunaos
prompt-install: true
dont-chroot: false
oem-setup: false
disable-cancel: false
disable-cancel-during-exec: false
hide-back-and-next-during-exec: true
quit-at-end: false
