---
efi:
  mountPoint: "/boot/efi"
  recommendedSize: 512MiB
  minimumSize: 32MiB
  label: "EFI"

userSwapChoices:
  - none
  - small
  - file

luksGeneration: luks2

drawNestedPartitions: false
alwaysShowPartitionLabels: true
allowManualPartitioning: true
initialPartitioningChoice: none
initialSwapChoice: none

defaultFileSystemType: "ext4"
availableFileSystemTypes: ["ext4", "btrfs", "xfs"]

essentialMounts: [ "live-*", "control", "ventoy" ]

lvm:
  enable: false
