---
# LUNA OS - Welcome Page Configuration

showSupportUrl: true
showKnownIssuesUrl: false
showReleaseNotesUrl: false
showDonateUrl: false

requirements:
  requiredStorage: 20
  requiredRam: 4
  check:
    - storage
    - ram
    - power
    - root
    - screen
  required:
    - storage
    - ram
    - root
