#!/bin/sh
set -e
lb config noauto \
    --architectures amd64 \
    --distribution noble \
    --binary-images iso \
    --archive-areas "main restricted universe multiverse" \
    --mirror-bootstrap "http://archive.ubuntu.com/ubuntu" \
    --mirror-chroot "http://archive.ubuntu.com/ubuntu" \
    --mirror-binary "http://archive.ubuntu.com/ubuntu" \
    --mirror-binary-security "http://security.ubuntu.com/ubuntu" \
    --security true \
    --bootloader "grub-efi" \
    --bootappend-live "boot=casper components console=ttyS0,115200n8 quiet splash username=luna hostname=luna live-config.user-fullname=Luna live-config.username=luna live-config.userpassword=luna" \
    --iso-application "Luna OS" \
    --iso-publisher "Luna OS Project" \
    --iso-volume "LUNA-OS" \
    --memtest none \
    --win32-loader false \
    --apt-recommends false \
    --apt-source-archives false \
    --cache-packages false \
    "${@}"
